### ISSUE TITLE
Typing issue with binding.pry 

### ISSUE THREAD

**Issue by enricribas** [influitive/stack-template#1]
If you run foreman, then binding.pry will not show the prompt properly. It works fine when you run the webpack server separately from the rails server. 

Not really something that can probably be fixed but it makes foreman kind of annoying to use.

**Comment by bradrobertson** [comment]
Ya we've seen this on our other projects. I dont' think foreman likes binding pry as it's buffering output from multiple sources. It *technically* works, but you can't see what you're typing. Don't think there's any way around this ???
